version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-master
    restart: unless-stopped
    user: root
    ports:
      - "9080:9080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./provisioning:/var/jenkins_home/provisioning
      - /var/run/docker.sock:/var/run/docker.sock
      - ./provisioning/scripts/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
    environment:
      - JENKINS_ADMIN_USER=admin
      - JENKINS_ADMIN_PASSWORD=admin123
      - JENKINS_OPTS=--httpPort=9080
      - JENKINS_AGENT_NAME=docker-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - CASC_JENKINS_CONFIG=/var/jenkins_home/provisioning/jenkins.yaml
      # Credentials environment variables
      - DOCKER_REGISTRY_USER=${DOCKER_REGISTRY_USER:-admin}
      - DOCKER_REGISTRY_PASS=${DOCKER_REGISTRY_PASS:-password123}
      - GITHUB_USER=${GITHUB_USER:-admin}
      - GITHUB_PAT=${GITHUB_PAT:-password123}
      # - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    env_file:
      - .env
    networks:
      - jenkins-network
    
    # depends_on:
    #   - jenkins-agent

  jenkins-agent:
    build:
      context: ./jenkins-agent
      dockerfile: Dockerfile
    container_name: jenkins-agent-dind
    restart: unless-stopped
    user: root
    privileged: true
    volumes:
      - jenkins_agent_workspace:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - JENKINS_URL=http://jenkins:9080
      - JENKINS_AGENT_NAME=docker-node
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=7ed1f6a185e24d8d197fe62847f36cd7f2c2a8efa84f701dfa1dc8e0e1721077
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local
  jenkins_agent_workspace:
    driver: local

networks:
  jenkins-network:
    driver: bridge