apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 5
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: prod-eks-karpenter-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: prod-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: prod-eks
  tags:
    managed_by: karpenter
    env: prod
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: "16"
    memory: 32Gi
